// ─── Types ────────────────────────────────────────────────────────────────────

export interface GigWorker {
  worker_id: string;
  name: string;
  gender: "male";
  platform: "Swiggy" | "Zomato" | "Blinkit" | "Uber" | "Ola" | "Porter";
  city: "Delhi" | "Mumbai" | "Bangalore" | "Hyderabad" | "Pune";
  city_tier: "Tier 1";
  days_active_last_30: number;
  avg_daily_income: number;
  hours_per_day: number;
  total_earnings_last_30_days: number;
  peak_hours: "morning" | "afternoon" | "evening" | "night";
  risk_zone: "low" | "medium" | "high";
  weather_exposure_days: number;
  aqi_exposure_days: number;
  joining_date: string;
  last_active_date: string;
}

// ─── Dataset ──────────────────────────────────────────────────────────────────
// 175 male gig workers across Delhi, Mumbai, Bangalore, Hyderabad, Pune
// Income correlates with hours_per_day × platform base rate × city multiplier
// total_earnings_last_30_days = avg_daily_income × days_active_last_30
// Risk zone: Delhi → AQI-driven | Mumbai → weather-driven | Rest → moderate
// Distribution: ~14% inactive (0–3 days), ~34% medium (5–15 days), ~52% heavy (20–30 days)

export const gigWorkers: GigWorker[] = [

  // ── DELHI (GW001–GW038) ─────────────────────────────────────────────────────
  // City multiplier: 1.15 | High AQI exposure | Moderate weather

  { worker_id: "GW001", name: "Rahul Sharma",    gender: "male", platform: "Uber",    city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 1320, hours_per_day: 10, total_earnings_last_30_days: 31680, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 5,  aqi_exposure_days: 16, joining_date: "2022-03-15", last_active_date: "2026-04-02" },
  { worker_id: "GW002", name: "Arjun Singh",      gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 28, avg_daily_income: 980,  hours_per_day: 9,  total_earnings_last_30_days: 27440, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 4,  aqi_exposure_days: 15, joining_date: "2021-11-20", last_active_date: "2026-04-03" },
  { worker_id: "GW003", name: "Vikram Yadav",     gender: "male", platform: "Zomato",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 14, avg_daily_income: 620,  hours_per_day: 6,  total_earnings_last_30_days: 8680,  peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 3,  aqi_exposure_days: 14, joining_date: "2023-07-10", last_active_date: "2026-03-28" },
  { worker_id: "GW004", name: "Deepak Kumar",     gender: "male", platform: "Ola",     city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 1260, hours_per_day: 11, total_earnings_last_30_days: 27720, peak_hours: "night",     risk_zone: "high",   weather_exposure_days: 6,  aqi_exposure_days: 17, joining_date: "2022-08-05", last_active_date: "2026-04-01" },
  { worker_id: "GW005", name: "Manish Gupta",     gender: "male", platform: "Blinkit", city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 460,  hours_per_day: 5,  total_earnings_last_30_days: 5060,  peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 3,  aqi_exposure_days: 12, joining_date: "2024-02-18", last_active_date: "2026-03-25" },
  { worker_id: "GW006", name: "Suresh Verma",     gender: "male", platform: "Porter",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1430, hours_per_day: 10, total_earnings_last_30_days: 37180, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 5,  aqi_exposure_days: 18, joining_date: "2021-06-22", last_active_date: "2026-04-03" },
  { worker_id: "GW007", name: "Rajesh Tiwari",    gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 435,  hours_per_day: 4,  total_earnings_last_30_days: 870,   peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 2,  aqi_exposure_days: 13, joining_date: "2023-04-30", last_active_date: "2026-02-28" },
  { worker_id: "GW008", name: "Pradeep Chauhan",  gender: "male", platform: "Uber",    city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1190, hours_per_day: 9,  total_earnings_last_30_days: 29750, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 7,  aqi_exposure_days: 16, joining_date: "2022-01-14", last_active_date: "2026-04-02" },
  { worker_id: "GW009", name: "Sumit Malhotra",   gender: "male", platform: "Zomato",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 8,  avg_daily_income: 620,  hours_per_day: 6,  total_earnings_last_30_days: 4960,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 10, joining_date: "2024-09-07", last_active_date: "2026-03-20" },
  { worker_id: "GW010", name: "Kapil Dev",        gender: "male", platform: "Blinkit", city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 735,  hours_per_day: 8,  total_earnings_last_30_days: 15435, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 3,  aqi_exposure_days: 15, joining_date: "2023-12-05", last_active_date: "2026-04-01" },
  { worker_id: "GW011", name: "Rohit Kashyap",    gender: "male", platform: "Ola",     city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 1,  avg_daily_income: 345,  hours_per_day: 3,  total_earnings_last_30_days: 345,   peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 8,  joining_date: "2025-03-22", last_active_date: "2026-02-15" },
  { worker_id: "GW012", name: "Anil Dubey",       gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 1200, hours_per_day: 11, total_earnings_last_30_days: 32400, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 6,  aqi_exposure_days: 17, joining_date: "2021-09-18", last_active_date: "2026-04-03" },
  { worker_id: "GW013", name: "Nitin Srivastava", gender: "male", platform: "Porter",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 1005, hours_per_day: 7,  total_earnings_last_30_days: 13065, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 5,  aqi_exposure_days: 14, joining_date: "2023-02-28", last_active_date: "2026-03-30" },
  { worker_id: "GW014", name: "Sandeep Rawat",    gender: "male", platform: "Zomato",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 825,  hours_per_day: 8,  total_earnings_last_30_days: 18975, peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 4,  aqi_exposure_days: 16, joining_date: "2022-05-11", last_active_date: "2026-04-02" },
  { worker_id: "GW015", name: "Naresh Bhadani",   gender: "male", platform: "Uber",    city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 10, avg_daily_income: 660,  hours_per_day: 5,  total_earnings_last_30_days: 6600,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 3,  aqi_exposure_days: 11, joining_date: "2024-06-15", last_active_date: "2026-03-22" },
  { worker_id: "GW016", name: "Vishal Meena",     gender: "male", platform: "Blinkit", city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 20, avg_daily_income: 825,  hours_per_day: 9,  total_earnings_last_30_days: 16500, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 5,  aqi_exposure_days: 15, joining_date: "2023-01-08", last_active_date: "2026-04-01" },
  { worker_id: "GW017", name: "Pankaj Jha",       gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 3,  avg_daily_income: 545,  hours_per_day: 5,  total_earnings_last_30_days: 1635,  peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 9,  joining_date: "2025-01-20", last_active_date: "2026-03-05" },
  { worker_id: "GW018", name: "Gaurav Pandey",    gender: "male", platform: "Ola",     city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 29, avg_daily_income: 1150, hours_per_day: 10, total_earnings_last_30_days: 33350, peak_hours: "night",     risk_zone: "high",   weather_exposure_days: 7,  aqi_exposure_days: 18, joining_date: "2021-07-04", last_active_date: "2026-04-03" },
  { worker_id: "GW019", name: "Amit Bharti",      gender: "male", platform: "Porter",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 15, avg_daily_income: 1150, hours_per_day: 8,  total_earnings_last_30_days: 17250, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 6,  aqi_exposure_days: 14, joining_date: "2022-10-30", last_active_date: "2026-03-31" },
  { worker_id: "GW020", name: "Harish Negi",      gender: "male", platform: "Zomato",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 930,  hours_per_day: 9,  total_earnings_last_30_days: 22320, peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 5,  aqi_exposure_days: 17, joining_date: "2022-03-17", last_active_date: "2026-04-02" },
  { worker_id: "GW021", name: "Tarun Saxena",     gender: "male", platform: "Uber",    city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 790,  hours_per_day: 6,  total_earnings_last_30_days: 9480,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 13, joining_date: "2024-04-22", last_active_date: "2026-03-27" },
  { worker_id: "GW022", name: "Vikas Solanki",    gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1090, hours_per_day: 10, total_earnings_last_30_days: 28340, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 6,  aqi_exposure_days: 16, joining_date: "2022-12-01", last_active_date: "2026-04-03" },
  { worker_id: "GW023", name: "Ravi Lodhi",       gender: "male", platform: "Blinkit", city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 276,  hours_per_day: 3,  total_earnings_last_30_days: 552,   peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 7,  joining_date: "2025-08-12", last_active_date: "2026-02-20" },
  { worker_id: "GW024", name: "Mahesh Dixit",     gender: "male", platform: "Porter",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 1500, hours_per_day: 11, total_earnings_last_30_days: 33000, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 8,  aqi_exposure_days: 15, joining_date: "2021-04-05", last_active_date: "2026-04-01" },
  { worker_id: "GW025", name: "Sunil Maurya",     gender: "male", platform: "Ola",     city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 805,  hours_per_day: 7,  total_earnings_last_30_days: 7245,  peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 12, joining_date: "2023-08-19", last_active_date: "2026-03-18" },
  { worker_id: "GW026", name: "Ankur Tripathi",   gender: "male", platform: "Zomato",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 825,  hours_per_day: 8,  total_earnings_last_30_days: 20625, peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 5,  aqi_exposure_days: 16, joining_date: "2022-06-08", last_active_date: "2026-04-02" },
  { worker_id: "GW027", name: "Kiran Chaudhary",  gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 14, avg_daily_income: 765,  hours_per_day: 7,  total_earnings_last_30_days: 10710, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 13, joining_date: "2023-11-25", last_active_date: "2026-03-29" },
  { worker_id: "GW028", name: "Mohit Bisht",      gender: "male", platform: "Uber",    city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 1190, hours_per_day: 9,  total_earnings_last_30_days: 24990, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 6,  aqi_exposure_days: 15, joining_date: "2022-09-14", last_active_date: "2026-04-01" },
  { worker_id: "GW029", name: "Hemant Batra",     gender: "male", platform: "Blinkit", city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 0,  avg_daily_income: 370,  hours_per_day: 4,  total_earnings_last_30_days: 0,     peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 5,  joining_date: "2025-07-30", last_active_date: "2026-01-28" },
  { worker_id: "GW030", name: "Sanjay Vashisht",  gender: "male", platform: "Ola",     city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 28, avg_daily_income: 1150, hours_per_day: 10, total_earnings_last_30_days: 32200, peak_hours: "night",     risk_zone: "high",   weather_exposure_days: 7,  aqi_exposure_days: 17, joining_date: "2021-10-12", last_active_date: "2026-04-03" },
  { worker_id: "GW031", name: "Ashok Rana",       gender: "male", platform: "Porter",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 860,  hours_per_day: 6,  total_earnings_last_30_days: 9460,  peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 12, joining_date: "2024-01-03", last_active_date: "2026-03-24" },
  { worker_id: "GW032", name: "Dinesh Mathur",    gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 1090, hours_per_day: 10, total_earnings_last_30_days: 25070, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 6,  aqi_exposure_days: 18, joining_date: "2022-02-28", last_active_date: "2026-04-02" },
  { worker_id: "GW033", name: "Vivek Kapoor",     gender: "male", platform: "Zomato",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 7,  avg_daily_income: 515,  hours_per_day: 5,  total_earnings_last_30_days: 3605,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 3,  aqi_exposure_days: 10, joining_date: "2024-10-15", last_active_date: "2026-03-16" },
  { worker_id: "GW034", name: "Sachin Tyagi",     gender: "male", platform: "Uber",    city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 1450, hours_per_day: 11, total_earnings_last_30_days: 34800, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 8,  aqi_exposure_days: 16, joining_date: "2021-05-20", last_active_date: "2026-04-03" },
  { worker_id: "GW035", name: "Nitesh Aggarwal",  gender: "male", platform: "Blinkit", city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 1,  avg_daily_income: 184,  hours_per_day: 2,  total_earnings_last_30_days: 184,   peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 8,  joining_date: "2025-10-08", last_active_date: "2026-02-10" },
  { worker_id: "GW036", name: "Aakash Garg",      gender: "male", platform: "Ola",     city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 805,  hours_per_day: 7,  total_earnings_last_30_days: 10465, peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 13, joining_date: "2023-06-18", last_active_date: "2026-03-26" },
  { worker_id: "GW037", name: "Lalit Mohan",      gender: "male", platform: "Swiggy",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 30, avg_daily_income: 980,  hours_per_day: 9,  total_earnings_last_30_days: 29400, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 5,  aqi_exposure_days: 19, joining_date: "2020-12-10", last_active_date: "2026-04-03" },
  { worker_id: "GW038", name: "Prem Nath",        gender: "male", platform: "Porter",  city: "Delhi",     city_tier: "Tier 1", days_active_last_30: 10, avg_daily_income: 860,  hours_per_day: 6,  total_earnings_last_30_days: 8600,  peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 3,  aqi_exposure_days: 11, joining_date: "2024-03-22", last_active_date: "2026-03-21" },

  // ── MUMBAI (GW039–GW076) ────────────────────────────────────────────────────
  // City multiplier: 1.25 | High weather exposure (monsoon) | Low AQI

  { worker_id: "GW039", name: "Rohan Patil",       gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1070, hours_per_day: 9,  total_earnings_last_30_days: 27820, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 10, aqi_exposure_days: 5,  joining_date: "2022-04-10", last_active_date: "2026-04-02" },
  { worker_id: "GW040", name: "Ketan Desai",       gender: "male", platform: "Uber",    city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1440, hours_per_day: 10, total_earnings_last_30_days: 36000, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 12, aqi_exposure_days: 4,  joining_date: "2021-08-15", last_active_date: "2026-04-03" },
  { worker_id: "GW041", name: "Nilesh Joshi",      gender: "male", platform: "Zomato",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 675,  hours_per_day: 6,  total_earnings_last_30_days: 8100,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 8,  aqi_exposure_days: 3,  joining_date: "2023-11-05", last_active_date: "2026-03-28" },
  { worker_id: "GW042", name: "Hardik Shah",       gender: "male", platform: "Blinkit", city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 800,  hours_per_day: 8,  total_earnings_last_30_days: 17600, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 9,  aqi_exposure_days: 5,  joining_date: "2023-02-20", last_active_date: "2026-04-01" },
  { worker_id: "GW043", name: "Chirag Mehta",      gender: "male", platform: "Ola",     city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 625,  hours_per_day: 5,  total_earnings_last_30_days: 5625,  peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 4,  joining_date: "2024-07-14", last_active_date: "2026-03-19" },
  { worker_id: "GW044", name: "Bhavin Patel",      gender: "male", platform: "Porter",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 28, avg_daily_income: 1500, hours_per_day: 10, total_earnings_last_30_days: 42000, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 13, aqi_exposure_days: 3,  joining_date: "2021-03-08", last_active_date: "2026-04-03" },
  { worker_id: "GW045", name: "Jayesh Thakkar",    gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 475,  hours_per_day: 4,  total_earnings_last_30_days: 950,   peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 2,  joining_date: "2025-05-18", last_active_date: "2026-02-22" },
  { worker_id: "GW046", name: "Hiren Gajjar",      gender: "male", platform: "Zomato",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 1010, hours_per_day: 9,  total_earnings_last_30_days: 27270, peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 11, aqi_exposure_days: 4,  joining_date: "2022-01-28", last_active_date: "2026-04-02" },
  { worker_id: "GW047", name: "Mitesh Modi",       gender: "male", platform: "Uber",    city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 14, avg_daily_income: 1005, hours_per_day: 7,  total_earnings_last_30_days: 14070, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 8,  aqi_exposure_days: 3,  joining_date: "2023-08-30", last_active_date: "2026-03-30" },
  { worker_id: "GW048", name: "Jignesh Parekh",    gender: "male", platform: "Blinkit", city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 1,  avg_daily_income: 300,  hours_per_day: 3,  total_earnings_last_30_days: 300,   peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 2,  joining_date: "2025-09-10", last_active_date: "2026-02-14" },
  { worker_id: "GW049", name: "Alpesh Bhatt",      gender: "male", platform: "Ola",     city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 1000, hours_per_day: 8,  total_earnings_last_30_days: 21000, peak_hours: "night",     risk_zone: "high",   weather_exposure_days: 9,  aqi_exposure_days: 5,  joining_date: "2023-04-05", last_active_date: "2026-04-01" },
  { worker_id: "GW050", name: "Paresh Vora",       gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 710,  hours_per_day: 6,  total_earnings_last_30_days: 7810,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 4,  joining_date: "2024-02-11", last_active_date: "2026-03-25" },
  { worker_id: "GW051", name: "Saurabh Nair",      gender: "male", platform: "Zomato",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 1125, hours_per_day: 10, total_earnings_last_30_days: 27000, peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 12, aqi_exposure_days: 3,  joining_date: "2022-07-22", last_active_date: "2026-04-02" },
  { worker_id: "GW052", name: "Santosh Kadam",     gender: "male", platform: "Porter",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 1090, hours_per_day: 7,  total_earnings_last_30_days: 14170, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 8,  aqi_exposure_days: 5,  joining_date: "2023-05-15", last_active_date: "2026-03-29" },
  { worker_id: "GW053", name: "Ramesh Jadhav",     gender: "male", platform: "Uber",    city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 29, avg_daily_income: 1500, hours_per_day: 11, total_earnings_last_30_days: 43500, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 14, aqi_exposure_days: 4,  joining_date: "2021-02-14", last_active_date: "2026-04-03" },
  { worker_id: "GW054", name: "Ganesh Salunke",    gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 8,  avg_daily_income: 595,  hours_per_day: 5,  total_earnings_last_30_days: 4760,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 3,  joining_date: "2024-08-25", last_active_date: "2026-03-17" },
  { worker_id: "GW055", name: "Prakash Mane",      gender: "male", platform: "Blinkit", city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 900,  hours_per_day: 9,  total_earnings_last_30_days: 20700, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 10, aqi_exposure_days: 5,  joining_date: "2022-10-18", last_active_date: "2026-04-01" },
  { worker_id: "GW056", name: "Yogesh Shinde",     gender: "male", platform: "Zomato",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 3,  avg_daily_income: 450,  hours_per_day: 4,  total_earnings_last_30_days: 1350,  peak_hours: "afternoon", risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 2,  joining_date: "2025-04-08", last_active_date: "2026-03-04" },
  { worker_id: "GW057", name: "Bhavesh Kulkarni",  gender: "male", platform: "Ola",     city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1125, hours_per_day: 9,  total_earnings_last_30_days: 28125, peak_hours: "night",     risk_zone: "high",   weather_exposure_days: 11, aqi_exposure_days: 4,  joining_date: "2022-05-30", last_active_date: "2026-04-02" },
  { worker_id: "GW058", name: "Tejas Sawant",      gender: "male", platform: "Porter",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 15, avg_daily_income: 1250, hours_per_day: 8,  total_earnings_last_30_days: 18750, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 9,  aqi_exposure_days: 5,  joining_date: "2023-01-14", last_active_date: "2026-03-31" },
  { worker_id: "GW059", name: "Atharv Wagmare",    gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 20, avg_daily_income: 950,  hours_per_day: 8,  total_earnings_last_30_days: 19000, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 10, aqi_exposure_days: 4,  joining_date: "2023-03-22", last_active_date: "2026-04-01" },
  { worker_id: "GW060", name: "Ruchir Karmarkar",  gender: "male", platform: "Uber",    city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 0,  avg_daily_income: 720,  hours_per_day: 5,  total_earnings_last_30_days: 0,     peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 2,  joining_date: "2025-11-02", last_active_date: "2026-01-31" },
  { worker_id: "GW061", name: "Dhruv Pendharkar",  gender: "male", platform: "Zomato",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1125, hours_per_day: 10, total_earnings_last_30_days: 29250, peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 12, aqi_exposure_days: 5,  joining_date: "2022-08-08", last_active_date: "2026-04-03" },
  { worker_id: "GW062", name: "Omkar Deshpande",   gender: "male", platform: "Blinkit", city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 10, avg_daily_income: 500,  hours_per_day: 5,  total_earnings_last_30_days: 5000,  peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 3,  joining_date: "2024-05-17", last_active_date: "2026-03-23" },
  { worker_id: "GW063", name: "Yash Bhosale",      gender: "male", platform: "Ola",     city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 1125, hours_per_day: 9,  total_earnings_last_30_days: 24750, peak_hours: "night",     risk_zone: "high",   weather_exposure_days: 10, aqi_exposure_days: 4,  joining_date: "2023-07-12", last_active_date: "2026-04-01" },
  { worker_id: "GW064", name: "Nikhil Chavan",     gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 710,  hours_per_day: 6,  total_earnings_last_30_days: 8520,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 4,  joining_date: "2024-01-28", last_active_date: "2026-03-28" },
  { worker_id: "GW065", name: "Vinayak Ghadge",    gender: "male", platform: "Porter",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 1500, hours_per_day: 11, total_earnings_last_30_days: 40500, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 13, aqi_exposure_days: 4,  joining_date: "2021-06-10", last_active_date: "2026-04-03" },
  { worker_id: "GW066", name: "Prasad Pawar",      gender: "male", platform: "Uber",    city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 860,  hours_per_day: 6,  total_earnings_last_30_days: 7740,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 3,  joining_date: "2024-09-03", last_active_date: "2026-03-21" },
  { worker_id: "GW067", name: "Sachin Palkar",     gender: "male", platform: "Zomato",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 1010, hours_per_day: 9,  total_earnings_last_30_days: 24240, peak_hours: "afternoon", risk_zone: "high",   weather_exposure_days: 11, aqi_exposure_days: 5,  joining_date: "2022-11-19", last_active_date: "2026-04-02" },
  { worker_id: "GW068", name: "Aditya Kamble",     gender: "male", platform: "Blinkit", city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 300,  hours_per_day: 3,  total_earnings_last_30_days: 600,   peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 2,  joining_date: "2025-06-25", last_active_date: "2026-02-18" },
  { worker_id: "GW069", name: "Swapnil Lonkar",    gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1190, hours_per_day: 10, total_earnings_last_30_days: 29750, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 12, aqi_exposure_days: 4,  joining_date: "2022-03-15", last_active_date: "2026-04-02" },
  { worker_id: "GW070", name: "Kunal Holkar",      gender: "male", platform: "Porter",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 14, avg_daily_income: 1090, hours_per_day: 7,  total_earnings_last_30_days: 15260, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 8,  aqi_exposure_days: 5,  joining_date: "2023-10-08", last_active_date: "2026-03-30" },
  { worker_id: "GW071", name: "Siddhesh Badve",    gender: "male", platform: "Uber",    city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 1150, hours_per_day: 8,  total_earnings_last_30_days: 24150, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 9,  aqi_exposure_days: 4,  joining_date: "2023-05-22", last_active_date: "2026-04-01" },
  { worker_id: "GW072", name: "Gaurav Shendkar",   gender: "male", platform: "Zomato",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 3,  avg_daily_income: 450,  hours_per_day: 4,  total_earnings_last_30_days: 1350,  peak_hours: "afternoon", risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 3,  joining_date: "2025-02-14", last_active_date: "2026-03-08" },
  { worker_id: "GW073", name: "Nilesh Mandlekar",  gender: "male", platform: "Blinkit", city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 28, avg_daily_income: 900,  hours_per_day: 9,  total_earnings_last_30_days: 25200, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 12, aqi_exposure_days: 5,  joining_date: "2022-01-06", last_active_date: "2026-04-03" },
  { worker_id: "GW074", name: "Harshad Kale",      gender: "male", platform: "Ola",     city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 750,  hours_per_day: 6,  total_earnings_last_30_days: 8250,  peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 4,  joining_date: "2024-04-19", last_active_date: "2026-03-25" },
  { worker_id: "GW075", name: "Rupesh Bendre",     gender: "male", platform: "Porter",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1500, hours_per_day: 10, total_earnings_last_30_days: 39000, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 11, aqi_exposure_days: 5,  joining_date: "2021-09-28", last_active_date: "2026-04-02" },
  { worker_id: "GW076", name: "Umesh Ghate",       gender: "male", platform: "Swiggy",  city: "Mumbai",    city_tier: "Tier 1", days_active_last_30: 8,  avg_daily_income: 595,  hours_per_day: 5,  total_earnings_last_30_days: 4760,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 3,  joining_date: "2024-06-30", last_active_date: "2026-03-17" },

  // ── BANGALORE (GW077–GW111) ─────────────────────────────────────────────────
  // City multiplier: 1.20 | Moderate weather | Low-moderate AQI

  { worker_id: "GW077", name: "Ravi Reddy",              gender: "male", platform: "Swiggy",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1025, hours_per_day: 9,  total_earnings_last_30_days: 25625, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 5,  joining_date: "2022-06-14", last_active_date: "2026-04-02" },
  { worker_id: "GW078", name: "Suresh Kumar N",          gender: "male", platform: "Uber",    city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 1380, hours_per_day: 10, total_earnings_last_30_days: 37260, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 4,  joining_date: "2021-10-20", last_active_date: "2026-04-03" },
  { worker_id: "GW079", name: "Manjunath H",             gender: "male", platform: "Zomato",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 648,  hours_per_day: 6,  total_earnings_last_30_days: 8424,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 5,  joining_date: "2023-09-02", last_active_date: "2026-03-29" },
  { worker_id: "GW080", name: "Venkatesh B",             gender: "male", platform: "Blinkit", city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 768,  hours_per_day: 8,  total_earnings_last_30_days: 16896, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 6,  joining_date: "2023-04-15", last_active_date: "2026-04-01" },
  { worker_id: "GW081", name: "Ganesh Murthy",           gender: "male", platform: "Ola",     city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 10, avg_daily_income: 600,  hours_per_day: 5,  total_earnings_last_30_days: 6000,  peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 4,  joining_date: "2024-06-08", last_active_date: "2026-03-23" },
  { worker_id: "GW082", name: "Kiran Raj",               gender: "male", platform: "Porter",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1500, hours_per_day: 10, total_earnings_last_30_days: 39000, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 8,  aqi_exposure_days: 5,  joining_date: "2022-01-18", last_active_date: "2026-04-03" },
  { worker_id: "GW083", name: "Nagaraj S",               gender: "male", platform: "Swiggy",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 456,  hours_per_day: 4,  total_earnings_last_30_days: 912,   peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 3,  joining_date: "2025-04-22", last_active_date: "2026-02-26" },
  { worker_id: "GW084", name: "Mahesh Babu",             gender: "male", platform: "Uber",    city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 1242, hours_per_day: 9,  total_earnings_last_30_days: 29808, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 5,  joining_date: "2022-07-05", last_active_date: "2026-04-02" },
  { worker_id: "GW085", name: "Prashanth M",             gender: "male", platform: "Zomato",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 756,  hours_per_day: 7,  total_earnings_last_30_days: 9072,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 4,  joining_date: "2023-11-28", last_active_date: "2026-03-28" },
  { worker_id: "GW086", name: "Sridhar Rao",             gender: "male", platform: "Blinkit", city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 20, avg_daily_income: 768,  hours_per_day: 8,  total_earnings_last_30_days: 15360, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 6,  joining_date: "2023-06-12", last_active_date: "2026-04-01" },
  { worker_id: "GW087", name: "Raghavendra N",           gender: "male", platform: "Porter",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 1,  avg_daily_income: 450,  hours_per_day: 3,  total_earnings_last_30_days: 450,   peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 2,  joining_date: "2025-08-18", last_active_date: "2026-02-12" },
  { worker_id: "GW088", name: "Sudhir Hebbar",           gender: "male", platform: "Ola",     city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 28, avg_daily_income: 1200, hours_per_day: 10, total_earnings_last_30_days: 33600, peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 5,  joining_date: "2021-12-08", last_active_date: "2026-04-03" },
  { worker_id: "GW089", name: "Anand Kulkarni",          gender: "male", platform: "Swiggy",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 570,  hours_per_day: 5,  total_earnings_last_30_days: 5130,  peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 4,  aqi_exposure_days: 4,  joining_date: "2024-03-07", last_active_date: "2026-03-20" },
  { worker_id: "GW090", name: "Shiva Kumar",             gender: "male", platform: "Zomato",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 972,  hours_per_day: 9,  total_earnings_last_30_days: 24300, peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 6,  joining_date: "2022-09-25", last_active_date: "2026-04-02" },
  { worker_id: "GW091", name: "Ramesh Gowda",            gender: "male", platform: "Blinkit", city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 14, avg_daily_income: 576,  hours_per_day: 6,  total_earnings_last_30_days: 8064,  peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 5,  joining_date: "2023-08-14", last_active_date: "2026-03-30" },
  { worker_id: "GW092", name: "Deepak Nayak",            gender: "male", platform: "Uber",    city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 1380, hours_per_day: 10, total_earnings_last_30_days: 31740, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 8,  aqi_exposure_days: 6,  joining_date: "2022-04-20", last_active_date: "2026-04-01" },
  { worker_id: "GW093", name: "Vikas Shetty",            gender: "male", platform: "Porter",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 3,  avg_daily_income: 750,  hours_per_day: 5,  total_earnings_last_30_days: 2250,  peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 3,  joining_date: "2025-01-15", last_active_date: "2026-03-07" },
  { worker_id: "GW094", name: "Arun Sharma",             gender: "male", platform: "Swiggy",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 912,  hours_per_day: 8,  total_earnings_last_30_days: 19152, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 5,  joining_date: "2023-02-28", last_active_date: "2026-04-01" },
  { worker_id: "GW095", name: "Naveen Bhat",             gender: "male", platform: "Zomato",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 648,  hours_per_day: 6,  total_earnings_last_30_days: 7128,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 4,  joining_date: "2024-05-10", last_active_date: "2026-03-26" },
  { worker_id: "GW096", name: "Girish Pai",              gender: "male", platform: "Blinkit", city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 864,  hours_per_day: 9,  total_earnings_last_30_days: 23328, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 6,  joining_date: "2022-08-22", last_active_date: "2026-04-03" },
  { worker_id: "GW097", name: "Lokesh Rao",              gender: "male", platform: "Ola",     city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 0,  avg_daily_income: 480,  hours_per_day: 4,  total_earnings_last_30_days: 0,     peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 2,  joining_date: "2025-10-30", last_active_date: "2026-01-25" },
  { worker_id: "GW098", name: "Sujith Nair",             gender: "male", platform: "Swiggy",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 1140, hours_per_day: 10, total_earnings_last_30_days: 27360, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 8,  aqi_exposure_days: 5,  joining_date: "2022-05-15", last_active_date: "2026-04-02" },
  { worker_id: "GW099", name: "Vinod Menon",             gender: "male", platform: "Porter",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 1050, hours_per_day: 7,  total_earnings_last_30_days: 13650, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 6,  joining_date: "2023-10-20", last_active_date: "2026-03-29" },
  { worker_id: "GW100", name: "Akhil Pillai",            gender: "male", platform: "Uber",    city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 1242, hours_per_day: 9,  total_earnings_last_30_days: 27324, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 5,  joining_date: "2023-01-12", last_active_date: "2026-04-01" },
  { worker_id: "GW101", name: "Sreejith Balakrishnan",   gender: "male", platform: "Zomato",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 8,  avg_daily_income: 540,  hours_per_day: 5,  total_earnings_last_30_days: 4320,  peak_hours: "afternoon", risk_zone: "low",    weather_exposure_days: 4,  aqi_exposure_days: 4,  joining_date: "2024-08-06", last_active_date: "2026-03-18" },
  { worker_id: "GW102", name: "Pradeep Gopinath",        gender: "male", platform: "Blinkit", city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 960,  hours_per_day: 10, total_earnings_last_30_days: 24960, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 8,  aqi_exposure_days: 6,  joining_date: "2022-03-08", last_active_date: "2026-04-03" },
  { worker_id: "GW103", name: "Manu Krishnan",           gender: "male", platform: "Ola",     city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 10, avg_daily_income: 720,  hours_per_day: 6,  total_earnings_last_30_days: 7200,  peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 5,  joining_date: "2024-01-22", last_active_date: "2026-03-22" },
  { worker_id: "GW104", name: "Nithin Raj",              gender: "male", platform: "Porter",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 29, avg_daily_income: 1500, hours_per_day: 11, total_earnings_last_30_days: 43500, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 9,  aqi_exposure_days: 5,  joining_date: "2021-07-30", last_active_date: "2026-04-03" },
  { worker_id: "GW105", name: "Jithin Thomas",           gender: "male", platform: "Swiggy",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 456,  hours_per_day: 4,  total_earnings_last_30_days: 912,   peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 3,  joining_date: "2025-07-14", last_active_date: "2026-02-28" },
  { worker_id: "GW106", name: "Bijoy Varghese",          gender: "male", platform: "Uber",    city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 1242, hours_per_day: 9,  total_earnings_last_30_days: 28566, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 6,  joining_date: "2022-11-05", last_active_date: "2026-04-02" },
  { worker_id: "GW107", name: "Anoop Kumawat",           gender: "male", platform: "Zomato",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 15, avg_daily_income: 756,  hours_per_day: 7,  total_earnings_last_30_days: 11340, peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 5,  joining_date: "2023-07-19", last_active_date: "2026-03-31" },
  { worker_id: "GW108", name: "Robin George",            gender: "male", platform: "Blinkit", city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 768,  hours_per_day: 8,  total_earnings_last_30_days: 16128, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 5,  joining_date: "2023-03-25", last_active_date: "2026-04-01" },
  { worker_id: "GW109", name: "Felix Anthony",           gender: "male", platform: "Porter",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 1050, hours_per_day: 7,  total_earnings_last_30_days: 12600, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 7,  aqi_exposure_days: 6,  joining_date: "2023-12-18", last_active_date: "2026-03-28" },
  { worker_id: "GW110", name: "Cyril Mathew",            gender: "male", platform: "Ola",     city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1200, hours_per_day: 10, total_earnings_last_30_days: 30000, peak_hours: "night",     risk_zone: "high",   weather_exposure_days: 8,  aqi_exposure_days: 5,  joining_date: "2022-06-28", last_active_date: "2026-04-03" },
  { worker_id: "GW111", name: "Albin Xavier",            gender: "male", platform: "Swiggy",  city: "Bangalore", city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 570,  hours_per_day: 5,  total_earnings_last_30_days: 5130,  peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 4,  aqi_exposure_days: 4,  joining_date: "2024-07-05", last_active_date: "2026-03-20" },

  // ── HYDERABAD (GW112–GW143) ─────────────────────────────────────────────────
  // City multiplier: 1.05 | Moderate weather & AQI | Mostly medium risk

  { worker_id: "GW112", name: "Suresh Reddy P",    gender: "male", platform: "Swiggy",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 900,  hours_per_day: 9,  total_earnings_last_30_days: 21600, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 8,  joining_date: "2022-09-10", last_active_date: "2026-04-02" },
  { worker_id: "GW113", name: "Ramakrishna T",     gender: "male", platform: "Uber",    city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1205, hours_per_day: 10, total_earnings_last_30_days: 30125, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 9,  joining_date: "2022-04-18", last_active_date: "2026-04-03" },
  { worker_id: "GW114", name: "Venkat Naidu",      gender: "male", platform: "Zomato",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 567,  hours_per_day: 6,  total_earnings_last_30_days: 6804,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 10, joining_date: "2023-08-25", last_active_date: "2026-03-28" },
  { worker_id: "GW115", name: "Srinivas Rao",      gender: "male", platform: "Ola",     city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 840,  hours_per_day: 8,  total_earnings_last_30_days: 18480, peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 8,  joining_date: "2023-02-14", last_active_date: "2026-04-01" },
  { worker_id: "GW116", name: "Gopal Krishna",     gender: "male", platform: "Blinkit", city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 336,  hours_per_day: 4,  total_earnings_last_30_days: 672,   peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 5,  joining_date: "2025-03-20", last_active_date: "2026-02-22" },
  { worker_id: "GW117", name: "Murali Das",        gender: "male", platform: "Porter",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1310, hours_per_day: 10, total_earnings_last_30_days: 34060, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 11, joining_date: "2022-01-30", last_active_date: "2026-04-03" },
  { worker_id: "GW118", name: "Bhanu Chander",     gender: "male", platform: "Swiggy",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 500,  hours_per_day: 5,  total_earnings_last_30_days: 5500,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 9,  joining_date: "2024-04-12", last_active_date: "2026-03-25" },
  { worker_id: "GW119", name: "Anil Babu",         gender: "male", platform: "Uber",    city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 1085, hours_per_day: 9,  total_earnings_last_30_days: 22785, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 10, joining_date: "2023-05-08", last_active_date: "2026-04-01" },
  { worker_id: "GW120", name: "Ravi Shankar",      gender: "male", platform: "Zomato",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 1,  avg_daily_income: 285,  hours_per_day: 3,  total_earnings_last_30_days: 285,   peak_hours: "afternoon", risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 4,  joining_date: "2025-09-15", last_active_date: "2026-02-08" },
  { worker_id: "GW121", name: "Shyam Dhar",        gender: "male", platform: "Blinkit", city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 756,  hours_per_day: 9,  total_earnings_last_30_days: 20412, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 12, joining_date: "2022-07-22", last_active_date: "2026-04-03" },
  { worker_id: "GW122", name: "Anand Varma",       gender: "male", platform: "Ola",     city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 735,  hours_per_day: 7,  total_earnings_last_30_days: 9555,  peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 9,  joining_date: "2023-11-10", last_active_date: "2026-03-29" },
  { worker_id: "GW123", name: "Vijay Kumar M",     gender: "male", platform: "Porter",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 1310, hours_per_day: 10, total_earnings_last_30_days: 30130, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 10, joining_date: "2022-10-05", last_active_date: "2026-04-02" },
  { worker_id: "GW124", name: "Raju Pillay",       gender: "male", platform: "Swiggy",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 10, avg_daily_income: 600,  hours_per_day: 6,  total_earnings_last_30_days: 6000,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 8,  joining_date: "2024-02-28", last_active_date: "2026-03-22" },
  { worker_id: "GW125", name: "Kishore Reddy",     gender: "male", platform: "Uber",    city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1205, hours_per_day: 10, total_earnings_last_30_days: 31330, peak_hours: "evening",   risk_zone: "high",   weather_exposure_days: 7,  aqi_exposure_days: 11, joining_date: "2022-05-14", last_active_date: "2026-04-03" },
  { worker_id: "GW126", name: "Vikram Naidu",      gender: "male", platform: "Zomato",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 3,  avg_daily_income: 378,  hours_per_day: 4,  total_earnings_last_30_days: 1134,  peak_hours: "afternoon", risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 6,  joining_date: "2025-01-08", last_active_date: "2026-03-06" },
  { worker_id: "GW127", name: "Srikanth L",        gender: "male", platform: "Blinkit", city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 672,  hours_per_day: 8,  total_earnings_last_30_days: 16128, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 10, joining_date: "2022-12-22", last_active_date: "2026-04-01" },
  { worker_id: "GW128", name: "Kiran Babu",        gender: "male", platform: "Porter",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 655,  hours_per_day: 5,  total_earnings_last_30_days: 5895,  peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 4,  aqi_exposure_days: 7,  joining_date: "2024-07-18", last_active_date: "2026-03-19" },
  { worker_id: "GW129", name: "Rajesh Mutha",      gender: "male", platform: "Swiggy",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 28, avg_daily_income: 900,  hours_per_day: 9,  total_earnings_last_30_days: 25200, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 11, joining_date: "2022-02-06", last_active_date: "2026-04-03" },
  { worker_id: "GW130", name: "Neeraj Ghosh",      gender: "male", platform: "Uber",    city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 14, avg_daily_income: 845,  hours_per_day: 7,  total_earnings_last_30_days: 11830, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 9,  joining_date: "2023-06-30", last_active_date: "2026-03-30" },
  { worker_id: "GW131", name: "Ashutosh Roy",      gender: "male", platform: "Zomato",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 756,  hours_per_day: 8,  total_earnings_last_30_days: 16632, peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 10, joining_date: "2023-03-17", last_active_date: "2026-04-01" },
  { worker_id: "GW132", name: "Partha Chatterjee", gender: "male", platform: "Blinkit", city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 0,  avg_daily_income: 252,  hours_per_day: 3,  total_earnings_last_30_days: 0,     peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 3,  joining_date: "2025-11-28", last_active_date: "2026-01-20" },
  { worker_id: "GW133", name: "Biplab Dey",        gender: "male", platform: "Ola",     city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 20, avg_daily_income: 840,  hours_per_day: 8,  total_earnings_last_30_days: 16800, peak_hours: "night",     risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 9,  joining_date: "2023-08-04", last_active_date: "2026-04-01" },
  { worker_id: "GW134", name: "Subhash Iyer",      gender: "male", platform: "Swiggy",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 600,  hours_per_day: 6,  total_earnings_last_30_days: 6600,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 8,  joining_date: "2024-03-25", last_active_date: "2026-03-24" },
  { worker_id: "GW135", name: "Ravindra Hegde",    gender: "male", platform: "Porter",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1310, hours_per_day: 10, total_earnings_last_30_days: 32750, peak_hours: "morning",   risk_zone: "high",   weather_exposure_days: 7,  aqi_exposure_days: 12, joining_date: "2022-08-12", last_active_date: "2026-04-02" },
  { worker_id: "GW136", name: "Pradeep Dalvi",     gender: "male", platform: "Uber",    city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 725,  hours_per_day: 6,  total_earnings_last_30_days: 8700,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 8,  joining_date: "2024-01-15", last_active_date: "2026-03-27" },
  { worker_id: "GW137", name: "Nikhil Soni",       gender: "male", platform: "Zomato",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 850,  hours_per_day: 9,  total_earnings_last_30_days: 19550, peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 10, joining_date: "2022-11-28", last_active_date: "2026-04-02" },
  { worker_id: "GW138", name: "Himanshu Jain",     gender: "male", platform: "Blinkit", city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 252,  hours_per_day: 3,  total_earnings_last_30_days: 504,   peak_hours: "morning",   risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 5,  joining_date: "2025-06-10", last_active_date: "2026-02-25" },
  { worker_id: "GW139", name: "Varun Agarwal",     gender: "male", platform: "Porter",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 1310, hours_per_day: 10, total_earnings_last_30_days: 35370, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 11, joining_date: "2022-03-08", last_active_date: "2026-04-03" },
  { worker_id: "GW140", name: "Akash Tomar",       gender: "male", platform: "Ola",     city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 8,  avg_daily_income: 525,  hours_per_day: 5,  total_earnings_last_30_days: 4200,  peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 3,  aqi_exposure_days: 7,  joining_date: "2024-09-22", last_active_date: "2026-03-18" },
  { worker_id: "GW141", name: "Sumit Bose",        gender: "male", platform: "Swiggy",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 798,  hours_per_day: 8,  total_earnings_last_30_days: 16758, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 9,  joining_date: "2023-04-28", last_active_date: "2026-04-01" },
  { worker_id: "GW142", name: "Santanu Ghosh",     gender: "male", platform: "Zomato",  city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 15, avg_daily_income: 660,  hours_per_day: 7,  total_earnings_last_30_days: 9900,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 10, joining_date: "2023-09-16", last_active_date: "2026-03-31" },
  { worker_id: "GW143", name: "Palash Mitra",      gender: "male", platform: "Uber",    city: "Hyderabad", city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 1085, hours_per_day: 9,  total_earnings_last_30_days: 26040, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 10, joining_date: "2022-07-15", last_active_date: "2026-04-02" },

  // ── PUNE (GW144–GW175) ──────────────────────────────────────────────────────
  // City multiplier: 1.00 | Low weather & AQI | Mostly low-medium risk

  { worker_id: "GW144", name: "Rahul Deshpande",        gender: "male", platform: "Swiggy",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 760,  hours_per_day: 8,  total_earnings_last_30_days: 17480, peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 4,  aqi_exposure_days: 5,  joining_date: "2022-11-14", last_active_date: "2026-04-02" },
  { worker_id: "GW145", name: "Omkar Bapat",            gender: "male", platform: "Uber",    city: "Pune",      city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1035, hours_per_day: 9,  total_earnings_last_30_days: 25875, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 6,  joining_date: "2022-04-30", last_active_date: "2026-04-03" },
  { worker_id: "GW146", name: "Nilesh Phadke",          gender: "male", platform: "Zomato",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 540,  hours_per_day: 6,  total_earnings_last_30_days: 5940,  peak_hours: "afternoon", risk_zone: "low",    weather_exposure_days: 3,  aqi_exposure_days: 5,  joining_date: "2024-01-20", last_active_date: "2026-03-25" },
  { worker_id: "GW147", name: "Vivek Bagwe",            gender: "male", platform: "Blinkit", city: "Pune",      city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 640,  hours_per_day: 8,  total_earnings_last_30_days: 14080, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 6,  joining_date: "2023-06-05", last_active_date: "2026-04-01" },
  { worker_id: "GW148", name: "Sanjeev Datar",          gender: "male", platform: "Ola",     city: "Pune",      city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 300,  hours_per_day: 3,  total_earnings_last_30_days: 600,   peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 3,  joining_date: "2025-04-14", last_active_date: "2026-02-24" },
  { worker_id: "GW149", name: "Pramod Palande",         gender: "male", platform: "Porter",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1250, hours_per_day: 10, total_earnings_last_30_days: 32500, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 5,  joining_date: "2021-12-28", last_active_date: "2026-04-03" },
  { worker_id: "GW150", name: "Kishor Sathe",           gender: "male", platform: "Swiggy",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 570,  hours_per_day: 6,  total_earnings_last_30_days: 7410,  peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 4,  aqi_exposure_days: 5,  joining_date: "2023-09-08", last_active_date: "2026-03-29" },
  { worker_id: "GW151", name: "Milind Marathe",         gender: "male", platform: "Zomato",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 810,  hours_per_day: 9,  total_earnings_last_30_days: 19440, peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 6,  joining_date: "2022-07-18", last_active_date: "2026-04-02" },
  { worker_id: "GW152", name: "Vinayak Modak",          gender: "male", platform: "Uber",    city: "Pune",      city_tier: "Tier 1", days_active_last_30: 1,  avg_daily_income: 460,  hours_per_day: 4,  total_earnings_last_30_days: 460,   peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 3,  joining_date: "2025-08-22", last_active_date: "2026-02-16" },
  { worker_id: "GW153", name: "Rohit Khole",            gender: "male", platform: "Blinkit", city: "Pune",      city_tier: "Tier 1", days_active_last_30: 20, avg_daily_income: 640,  hours_per_day: 8,  total_earnings_last_30_days: 12800, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 5,  joining_date: "2023-03-15", last_active_date: "2026-04-01" },
  { worker_id: "GW154", name: "Akshay More",            gender: "male", platform: "Ola",     city: "Pune",      city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 500,  hours_per_day: 5,  total_earnings_last_30_days: 4500,  peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 3,  aqi_exposure_days: 5,  joining_date: "2024-06-12", last_active_date: "2026-03-21" },
  { worker_id: "GW155", name: "Sudhir Bhosale",         gender: "male", platform: "Porter",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 27, avg_daily_income: 1250, hours_per_day: 10, total_earnings_last_30_days: 33750, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 6,  joining_date: "2022-02-08", last_active_date: "2026-04-03" },
  { worker_id: "GW156", name: "Abhijit Dhole",          gender: "male", platform: "Swiggy",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 3,  avg_daily_income: 380,  hours_per_day: 4,  total_earnings_last_30_days: 1140,  peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 2,  aqi_exposure_days: 4,  joining_date: "2025-02-05", last_active_date: "2026-03-09" },
  { worker_id: "GW157", name: "Suhas Karve",            gender: "male", platform: "Zomato",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 720,  hours_per_day: 8,  total_earnings_last_30_days: 15120, peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 5,  joining_date: "2023-01-22", last_active_date: "2026-04-01" },
  { worker_id: "GW158", name: "Naren Naik",             gender: "male", platform: "Uber",    city: "Pune",      city_tier: "Tier 1", days_active_last_30: 12, avg_daily_income: 805,  hours_per_day: 7,  total_earnings_last_30_days: 9660,  peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 6,  joining_date: "2023-10-28", last_active_date: "2026-03-28" },
  { worker_id: "GW159", name: "Mahesh Gadgil",          gender: "male", platform: "Blinkit", city: "Pune",      city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 720,  hours_per_day: 9,  total_earnings_last_30_days: 18000, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 6,  joining_date: "2022-08-14", last_active_date: "2026-04-02" },
  { worker_id: "GW160", name: "Vasant Nimkar",          gender: "male", platform: "Ola",     city: "Pune",      city_tier: "Tier 1", days_active_last_30: 8,  avg_daily_income: 500,  hours_per_day: 5,  total_earnings_last_30_days: 4000,  peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 3,  aqi_exposure_days: 4,  joining_date: "2024-04-25", last_active_date: "2026-03-18" },
  { worker_id: "GW161", name: "Arun Tilak",             gender: "male", platform: "Porter",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 1125, hours_per_day: 9,  total_earnings_last_30_days: 24750, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 6,  joining_date: "2022-10-15", last_active_date: "2026-04-01" },
  { worker_id: "GW162", name: "Girish Dandekar",        gender: "male", platform: "Swiggy",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 0,  avg_daily_income: 285,  hours_per_day: 3,  total_earnings_last_30_days: 0,     peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 0,  aqi_exposure_days: 2,  joining_date: "2025-12-08", last_active_date: "2026-01-28" },
  { worker_id: "GW163", name: "Saurabh Lele",           gender: "male", platform: "Uber",    city: "Pune",      city_tier: "Tier 1", days_active_last_30: 28, avg_daily_income: 1150, hours_per_day: 10, total_earnings_last_30_days: 32200, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 6,  joining_date: "2021-11-02", last_active_date: "2026-04-03" },
  { worker_id: "GW164", name: "Chandrashekhar Gokhale", gender: "male", platform: "Zomato",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 14, avg_daily_income: 630,  hours_per_day: 7,  total_earnings_last_30_days: 8820,  peak_hours: "afternoon", risk_zone: "low",    weather_exposure_days: 4,  aqi_exposure_days: 5,  joining_date: "2023-07-12", last_active_date: "2026-03-30" },
  { worker_id: "GW165", name: "Ajay Kulkarni",          gender: "male", platform: "Blinkit", city: "Pune",      city_tier: "Tier 1", days_active_last_30: 23, avg_daily_income: 640,  hours_per_day: 8,  total_earnings_last_30_days: 14720, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 7,  joining_date: "2022-05-28", last_active_date: "2026-04-02" },
  { worker_id: "GW166", name: "Devendra Thakur",        gender: "male", platform: "Ola",     city: "Pune",      city_tier: "Tier 1", days_active_last_30: 10, avg_daily_income: 600,  hours_per_day: 6,  total_earnings_last_30_days: 6000,  peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 3,  aqi_exposure_days: 5,  joining_date: "2024-03-18", last_active_date: "2026-03-23" },
  { worker_id: "GW167", name: "Hemant Rane",            gender: "male", platform: "Porter",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 26, avg_daily_income: 1250, hours_per_day: 10, total_earnings_last_30_days: 32500, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 6,  joining_date: "2022-01-10", last_active_date: "2026-04-03" },
  { worker_id: "GW168", name: "Shekhar Jog",            gender: "male", platform: "Swiggy",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 2,  avg_daily_income: 380,  hours_per_day: 4,  total_earnings_last_30_days: 760,   peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 1,  aqi_exposure_days: 3,  joining_date: "2025-07-05", last_active_date: "2026-02-18" },
  { worker_id: "GW169", name: "Vikas Nene",             gender: "male", platform: "Uber",    city: "Pune",      city_tier: "Tier 1", days_active_last_30: 21, avg_daily_income: 920,  hours_per_day: 8,  total_earnings_last_30_days: 19320, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 5,  joining_date: "2023-04-10", last_active_date: "2026-04-01" },
  { worker_id: "GW170", name: "Tushar Vaidya",          gender: "male", platform: "Zomato",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 13, avg_daily_income: 540,  hours_per_day: 6,  total_earnings_last_30_days: 7020,  peak_hours: "afternoon", risk_zone: "medium", weather_exposure_days: 4,  aqi_exposure_days: 6,  joining_date: "2023-12-05", last_active_date: "2026-03-28" },
  { worker_id: "GW171", name: "Siddharth Ganu",         gender: "male", platform: "Blinkit", city: "Pune",      city_tier: "Tier 1", days_active_last_30: 24, avg_daily_income: 720,  hours_per_day: 9,  total_earnings_last_30_days: 17280, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 6,  joining_date: "2022-09-22", last_active_date: "2026-04-02" },
  { worker_id: "GW172", name: "Kedar Bhide",            gender: "male", platform: "Ola",     city: "Pune",      city_tier: "Tier 1", days_active_last_30: 9,  avg_daily_income: 500,  hours_per_day: 5,  total_earnings_last_30_days: 4500,  peak_hours: "night",     risk_zone: "low",    weather_exposure_days: 3,  aqi_exposure_days: 4,  joining_date: "2024-08-14", last_active_date: "2026-03-20" },
  { worker_id: "GW173", name: "Sachin Agashe",          gender: "male", platform: "Porter",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 25, avg_daily_income: 1250, hours_per_day: 10, total_earnings_last_30_days: 31250, peak_hours: "morning",   risk_zone: "medium", weather_exposure_days: 6,  aqi_exposure_days: 7,  joining_date: "2022-03-25", last_active_date: "2026-04-03" },
  { worker_id: "GW174", name: "Prakash Gosavi",         gender: "male", platform: "Swiggy",  city: "Pune",      city_tier: "Tier 1", days_active_last_30: 11, avg_daily_income: 475,  hours_per_day: 5,  total_earnings_last_30_days: 5225,  peak_hours: "evening",   risk_zone: "low",    weather_exposure_days: 3,  aqi_exposure_days: 5,  joining_date: "2024-05-30", last_active_date: "2026-03-25" },
  { worker_id: "GW175", name: "Vinod Waghmare",         gender: "male", platform: "Uber",    city: "Pune",      city_tier: "Tier 1", days_active_last_30: 22, avg_daily_income: 920,  hours_per_day: 8,  total_earnings_last_30_days: 20240, peak_hours: "evening",   risk_zone: "medium", weather_exposure_days: 5,  aqi_exposure_days: 6,  joining_date: "2023-02-18", last_active_date: "2026-04-01" },
];

// ─── Utility Functions ────────────────────────────────────────────────────────

/**
 * Returns a random worker from the dataset.
 */
export function getRandomWorker(): GigWorker {
  return gigWorkers[Math.floor(Math.random() * gigWorkers.length)];
}

/**
 * Returns all workers from the specified city.
 * Case-insensitive match.
 */
export function getWorkersByCity(city: string): GigWorker[] {
  const normalized = city.trim().toLowerCase();
  return gigWorkers.filter(w => w.city.toLowerCase() === normalized);
}

/**
 * Returns all workers in the high risk zone.
 */
export function getHighRiskWorkers(): GigWorker[] {
  return gigWorkers.filter(w => w.risk_zone === "high");
}

// ─── Derived Stats (bonus helpers) ───────────────────────────────────────────

/**
 * Returns workers grouped by city with aggregate stats.
 */
export function getCityStats() {
  const cities = ["Delhi", "Mumbai", "Bangalore", "Hyderabad", "Pune"] as const;
  return cities.map(city => {
    const workers = getWorkersByCity(city);
    const active = workers.filter(w => w.days_active_last_30 >= 20);
    const totalEarnings = workers.reduce((s, w) => s + w.total_earnings_last_30_days, 0);
    const avgIncome = Math.round(totalEarnings / workers.length);
    const highRisk = workers.filter(w => w.risk_zone === "high").length;
    return { city, total: workers.length, active: active.length, avgIncome, highRisk };
  });
}

/**
 * Returns inactive workers (0–3 days active in last 30 days).
 */
export function getInactiveWorkers(): GigWorker[] {
  return gigWorkers.filter(w => w.days_active_last_30 <= 3);
}

/**
 * Returns heavy workers (20+ days active in last 30 days).
 */
export function getHeavyWorkers(): GigWorker[] {
  return gigWorkers.filter(w => w.days_active_last_30 >= 20);
}
